# Generated by Django 4.2.3 on 2023-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0002_alter_candidate_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
